# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "packages/cli"
      - "packages/z"
      - "packages/nestjs-zod"
    allow:
      - dependency-type: development
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directories:
      - "packages/example"
      - "packages/example-esm"
      - "packages/example-dual-zods"
    schedule:
      interval: "weekly"
